ComicCollection/urls.py
from django.urls import path

import ComicCollection.views
from .views import PublisherListView, comic_collection_landing

app_name = "ComicCollection"
urlpatterns = [
    path("", comic_collection_landing, name="publisher-landing"),
    path("Publishers/", PublisherListView.as_view(), name="publisher-list"),
]

LarfleezeComicsWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("ComicCollection.urls")),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ComicCollection/models.py
from django.contrib.auth.models import User
from django.db import models


class Publisher(models.Model):
    publisher_name = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Series(models.Model):
    name = models.CharField(max_length=200)
    start_year = models.IntegerField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    count_issues = models.IntegerField()
    count_issues_in_collection = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Issue(models.Model):
    issue_number = models.DecimalField(max_digits=10, decimal_places=2)
    title = models.CharField(max_length=200)
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    cover_root_path = models.CharField()
    cover_date = models.DateField()
    stores_date = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

ComicCollection/views.py
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import render

from django.views.generic import ListView

from ComicCollection.models import Publisher


# Create your views here.
def index(request):
     key = settings.COMICVINE_API_KEY
     return HttpResponse("Your Comic-Vine Api Key is " + key)


class PublisherListView(ListView):
    model = Publisher
    template_name = "ComicCollection/publishers_list.html"


def comic_collection_landing(request):
    return render(request, "ComicCollection/landing.html")

ComicCollection/templates/ComicCollection/base.html
{% extends "skeleton.html" %}

{% block base_template_content %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 h-100 d-inline-block">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Comic Collection</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button type="button"
                        class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
                    <svg class="bi">
                        <use xlink:href="#calendar3"></use>
                    </svg>
                    This week
                </button>
            </div>
        </div>
        {% block comics_collection_content %}{% endblock %}
    </main>
{% endblock %}

ComicCollection/templates/ComicCollection/landing.html
{% extends "ComicCollection/base.html" %}

ComicCollection/templates/ComicCollection/publishers_list.html
{% extends "ComicCollection/base.html" %}

{% block comics_collection_content %}
<h2>Publishers</h2>

<div class="table-responsive small">
    <ul class="list-group list-group-flush">
        {% for publisher in object_list %}
            <li class="list-group-item">{{  publisher.publisher_name }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/skeleton.html
{% load static %}
<html lang="en" data-bs-theme="dark">
<head>
    <link rel="stylesheet" href="{% static 'ComicCollection/color-modes.js' %}">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Larfleeze Comic Collection</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
    <link rel="stylesheet" href="{% static 'ComicCollection/css@3' %}">
    <link rel="stylesheet" href="{% static 'ComicCollection/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Favicons -->
    <meta name="theme-color" content="#712cf9">

    <!-- Custom styles for this template -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'ComicCollection/dashboard.css' %}" rel="stylesheet">
</head>
<body>

<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">Larfleeze</a>

    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false"
                    aria-label="Toggle search">
                <svg class="bi">
                    <use xlink:href="#search"></use>
                </svg>
            </button>
        </li>
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">
                <svg class="bi">
                    <use xlink:href="#list"></use>
                </svg>
            </button>
        </li>
    </ul>

    <div id="navbarSearch" class="navbar-search w-100 collapse">
        <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
            <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
                 aria-labelledby="sidebarMenuLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="sidebarMenuLabel">Larfleeze</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
                            aria-label="Close"></button>
                </div>
                <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                        <span>Comic Collection</span><i class="bi bi-book"></i>
                    </h6>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="#">
                                <i class="bi bi-book"></i>Comics
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="#">
                                <i class="bi bi-list-columns"></i>Series
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'ComicCollection:publisher-list'%}">
                                <i class="bi bi-printer-fill"></i>Publishers
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        {% block base_template_content %}{% endblock %}

    </div>
    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js"
        integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="{% static 'ComicCollection/dashboard.js' %}"></script>
</body>
</html>